### ISSUE TITLE
ACL columns should be indicated between " on the documentation or equals method changed to equalsIgnoreCase

### ISSUE THREAD

**Issue by samuelzvir** [googlegsa/database#1]
The documentation at http://static.googleusercontent.com/media/www.google.com/en/us/support/enterprise/static/gsa/docs/admin/connectors/40/404/DeployingtheConnectorforDatabases.pdf should indicate the alias between " for 
GSA_PERMIT_USERS, GSA_DENY_USERS, GSA_PERMIT_GROUPS, GSA_DENY_GROUPS and GSA_TIMESTAMP to guarantee the upper case, because the DatabaseAdaptor class uses equals instead of equalsIgnoreCase. Another option is to change the equals method to equalsIgnoreCase. It's simple but needed.

**Comment by wiarlawd** [comment]
This needs to be looked at further, but I wanted to comment for later that quoted identifiers are not always uppercased. This is DBMS and configuration specific, and can be checked (probably not conclusively) in DatabaseMetaData. Secondly, it is possible to configure databases to be case-sensitive in identifiers (SQL Server is a well-known culprit), and equalsIgnoreCase may not always be the right thing to do, either.

**Comment by samuelzvir** [comment]
Right.
Probably the best choice is a documentation update explaining that the identifiers need to be uppercased 
independently of the way. 

Thank you @wiarlawd !
