### ISSUE TITLE
database columns should be metadata by default

### ISSUE THREAD

**Issue by michaelcizmar** [googlegsa/database#3]
"The default is an empty string, which means no column will be used as metadata. Database
metadata columns are optional."

The general use case would be that you would want to specify the columns or modify them in the query.  If you did not want them passed, you would generally choose to not specify them.

**Comment by myk-google** [comment]
You are commenting on the documentation, correct?   This will be addressed in the 4.1.1 docs (in the section for the new urlAndMetadataLister mode):

> Google recommends that you specify columns by using the db.metadataColumns configuration option when using this mode of operation. For example:
> 
> db.metadataColumns=name:name,dbcol:gsa_metaname

**Comment by michaelcizmar** [comment]
No.  I am saying that why doesn't the connector by default take all of the columns and make them metadata.  So, the intuitive feature is that if you do not list any metadata columns, it should make all of the returned columns metadata.  It's the opposite.

**Comment by myk-google** [comment]
I spoke with the original implementer of the Database Adaptor code, and his reasoning (as to why not to include everything by default) is that it could too-easily expose sensitive information.  It's more secure to have to specify the columns you want exported as metadata than to just assume that everything should be exported.  (Getting a list of all the columns is fairly easy with "describe table" -- so doing that (once) to retrieve all the columns, and copying them in to the configuration file (as well as assigning a name for the key on the GSA side) is not a lot of work; having the Adaptor do that work (at the risk of possibly exposing sensitive information) is not a good trade-off.   But we _will_ consider adding this (as a feature) in the future.

**Comment by michaelcizmar** [comment]
I'm not sure that explanation makes sense.  Let me explain:

I thought that the property is not describing a table but specifying at query that is the document.  If true, you as the administrator should specify in your query what you would like indexed.  If you do not want it indexed, you should not specify it in your query.  You are saying, it's a security concern that it be metadata?  How is it also not a security concern to have it indexed?  Why is the column in the result set if not to be indexed.

The GSA has no field level security so why in this one instance are we going to care which fields are listed.  The GSA itself indexes any and all metadata.  The Sharepoint connector...indexes all metadata.  You don't go in and explicitly name every metadata column in Sharepoint.

Thanks!

**Comment by cjohnson78** [comment]
Having written and deployed my own "Database Connector" for GSA, I agree with Michael.  The SQL Query allows the client to "select" which columns they want indexed in the GSA.  It seems redundant to _also_ have to list the columns again for inclusion in metadata.  That is typically the whole point of using this connector.

One compromise could be to include an option, such as "db.includeAllMetadataColumns" that automatically includes every available column, instead of having to list them out again.

I admit that listing them out isn't that hard, but it is also likely to cause confusion for users, since like I said, I think most people expect it to do this.

**Comment by myk-google** [comment]
Introducing  "db.includeAllMetadataColumns" (which will default to "false", to maintain the existing behavior) and setting it to "true", and leaving db.metadataColumns blank) will use all query results as Michael requests.  I'll write the code this week, and it should make it in to the next release.

**Comment by myk-google** [comment]
Submitted as https://github.com/googlegsa/database/commit/96c3c483199fd77e729064fff3bb44cd88f84359 .

**Comment by michaelcizmar** [comment]
I think you missed this.  I don't want to specify the columns in db.metadataColumns.  I want the columns that are specified in the query to be used.  You should be inspecting your resultset from the docQuery to determine what metadata to use.

**Comment by myk-google** [comment]
If you set "`db.includeAllColumnsAsMetadata`" to "`true`" and leave "`db.metadataColumns`" set to "", then **all** columns that are returned in the query are treated as metadata.  Isn't that the behavior that you wanted?

**Comment by myk-google** [comment]
The code in what is now lines 283-293 of DatabaseAdaptor.java:

```
      // Generate response metadata first.
      ResultSetMetaData rsMetaData = rs.getMetaData();
      int numberOfColumns = rsMetaData.getColumnCount();
      for (int i = 1; i < (numberOfColumns + 1); i++) {
        String columnName = rsMetaData.getColumnName(i);
        Object value = rs.getObject(i);
        String key = metadataColumns.getMetadataName(columnName);
        if (key != null) {
          resp.addMetadata(key, "" + value);
        }
      }

```

will now (when `"db.includeAllColumnsAsMetadata"` is `"true"` and `"db.metadataColumns"` is `""`) behave as though the for loop read:

```
      for (int i = 1; i < (numberOfColumns + 1); i++) {
        String columnName = rsMetaData.getColumnName(i);
        Object value = rs.getObject(i);
        if (columnName != null) {
          resp.addMetadata(columnName, "" + value);
        }
      }

```

**Comment by michaelcizmar** [comment]
That's perfect.  I looked at the test case and didn't see that.  Great!
